version = 0.1

[default]
[default.global.parameters]
stack_name = "alexa-llm-chat"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "alexa-llm-chat"
region = "us-east-1"
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

# Development environment
[dev]
[dev.deploy.parameters]
stack_name = "alexa-llm-chat-dev"
s3_prefix = "alexa-llm-chat-dev"
parameter_overrides = [
    "Environment=dev"
]

# Staging environment
[staging]
[staging.deploy.parameters]
stack_name = "alexa-llm-chat-staging"
s3_prefix = "alexa-llm-chat-staging"
parameter_overrides = [
    "Environment=staging"
]

# Production environment
[prod]
[prod.deploy.parameters]
stack_name = "alexa-llm-chat-prod"
s3_prefix = "alexa-llm-chat-prod"
parameter_overrides = [
    "Environment=prod"
]